import assert from 'node:assert/strict';
import {createRequire} from 'node:module';
import {writeFile} from 'node:fs/promises';
const require=createRequire('C:/Users/user/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright/package.json');const {chromium}=require('playwright');
const browser=await chromium.launch({channel:'msedge',headless:true});const context=await browser.newContext({viewport:{width:1440,height:1000}});const page=await context.newPage();await page.goto('http://localhost:4173');
const results=[];
await page.locator('#todo-list [data-drag="0"]').dragTo(page.locator('.todo-row').nth(2));assert.equal(await page.locator('.todo-row').last().locator('label span').textContent(),'오늘 할 일 정리');results.push('TO DO mouse drag reorder');
await page.getByRole('button',{name:'아이디어 메모 할 일 수정',exact:true}).click();await page.getByLabel('할 일',{exact:true}).fill('수정된 할 일');await page.getByRole('button',{name:'저장',exact:true}).click();assert.equal(await page.getByText('수정된 할 일',{exact:true}).count(),1);
await page.getByRole('button',{name:'수정된 할 일 할 일 삭제',exact:true}).click();await page.getByRole('button',{name:'취소',exact:true}).last().click();assert.equal(await page.getByText('수정된 할 일',{exact:true}).count(),1);await page.getByRole('button',{name:'수정된 할 일 할 일 삭제',exact:true}).click();await page.locator('#delete-confirm').click();assert.equal(await page.getByText('수정된 할 일',{exact:true}).count(),0);results.push('TO DO edit/delete/cancel');
await page.getByRole('button',{name:'하루 계획 일정 수정',exact:true}).click();await page.getByLabel('제목',{exact:true}).fill('수정된 일정');await page.getByLabel('종료 시간').fill('08:00');await page.getByRole('button',{name:'저장',exact:true}).click();assert.match(await page.locator('#editor-error').textContent(),/종료/);await page.getByLabel('종료 시간').fill('10:30');await page.getByRole('button',{name:'저장',exact:true}).click();await page.getByRole('button',{name:'수정된 일정 일정 삭제',exact:true}).click();await page.locator('#delete-confirm').click();assert.equal(await page.getByText('수정된 일정',{exact:true}).count(),0);results.push('Schedule edit/delete/reversed time validation');
const days=page.locator('#month-days button');await days.last().click();assert.match(await page.locator('#agenda').textContent(),/등록된 일정이 없어요/);await page.locator('#today').click();assert.match(await page.locator('#agenda').textContent(),/예시 미팅/);results.push('Date switch and return today');
const note=page.locator('.note').first(),handle=note.locator('[data-grip]');await handle.scrollIntoViewIfNeeded();const before=await note.boundingBox(),grip=await handle.boundingBox();await page.mouse.move(grip.x+10,grip.y+10);await page.mouse.down();await page.mouse.move(grip.x+80,grip.y+40,{steps:5});await page.mouse.up();const after=await note.boundingBox();assert.ok(after.x>before.x);await note.getByRole('button',{name:'메모 수정',exact:true}).click();await page.getByLabel('메모 내용').fill('수정된 메모');await page.getByRole('button',{name:'저장',exact:true}).click();await page.locator('.note').filter({hasText:'수정된 메모'}).getByRole('button',{name:'메모 삭제',exact:true}).click();await page.locator('#delete-confirm').click();assert.equal(await page.getByText('수정된 메모',{exact:true}).count(),0);results.push('Sticky note mouse drag/edit/delete');
await page.locator('#focus-min').fill('0.2');await page.locator('#break-min').fill('0.1');await page.locator('#timer-start').click();await page.locator('#timer-pause').click();const paused=await page.locator('#timer-display').textContent();await page.waitForTimeout(1000);assert.equal(await page.locator('#timer-display').textContent(),paused);await page.locator('#timer-reset').click();assert.equal(await page.locator('#timer-display').textContent(),'00:00');results.push('Timer pause/reset');
await page.setViewportSize({width:390,height:844});await page.reload();const positions=await page.locator('.note').evaluateAll(nodes=>nodes.map(n=>({bottom:n.offsetTop+n.offsetHeight,board:n.parentElement.clientHeight})));assert.ok(positions.every(n=>n.bottom<=n.board));results.push('Narrow note bounds');
// WCAG relative luminance calculation: explicit color pairs, independent of CSS rendering.
const luminance=hex=>{const rgb=hex.match(/\w\w/g).map(v=>parseInt(v,16)/255).map(v=>v<=.04045?v/12.92:((v+.055)/1.055)**2.4);return .2126*rgb[0]+.7152*rgb[1]+.0722*rgb[2];};
const pairs=[['본문','172142','FFFFFF'],['보조','526079','FFFFFF'],['주요 버튼','FFFFFF','5B3FD6'],['선택 면','4930B8','EEE9FF'],['입력 경계','78849B','FFFFFF']].map(([name,a,b])=>{const la=luminance(a),lb=luminance(b);return {name,ratio:Number(((Math.max(la,lb)+.05)/(Math.min(la,lb)+.05)).toFixed(2))};});assert.ok(pairs.every(p=>p.ratio>=(p.name==='입력 경계'?3:4.5)));await writeFile('../../review/review-assets/interaction-results.json',JSON.stringify({results,pairs},null,2));console.log(JSON.stringify({results,pairs},null,2));await browser.close();
